package com.etf.rti.p1.ui.questions;

public enum QuestionAskedForType {
    CORRECT_SEQUENCE_FOR_FIRST_NONTERMINAL,
    CORRECT_RULE_WHICH_SHOULD_BE_ADDED,
    CORRECT_GRAMMAR_FOR_FIRST_NONTERMINAL_SEQUENCE
}
