<nastup> ::= <grupa>∆<vreme>∆<minut> | <nastup>,∆<vreme>∆<minut>
<grupa> ::= <rec> | <grupa>∆<rec>
<rec> ::= <slovo> | <rec><slovo>
<vreme> ::= <sat>:<minut>
<sat> ::= <cifra> | 1<cifra> | 2<cifra>
<minut> ::= <cifra><cifra>
<slovo> ::= a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z
<cifra> ::= 0|1|2|3|4|5|6|7|8|9